# Generated by Django 3.1 on 2020-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
