# Generated by Django 3.1 on 2020-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='attachment',
            field=models.URLField(),
        ),
    ]
